package:
  name: oslo.concurrency
  version: "1.8.2"

source:
  fn: oslo.concurrency-1.8.2.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.concurrency/oslo.concurrency-1.8.2.tar.gz
  md5: 1ba5ae8bdbb9c12c1b6baa8e3d400b7f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oslo.concurrency = oslo.concurrency:main
    #
    # Would create an entry point called oslo.concurrency that calls oslo.concurrency.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3

  run:
    - python
    - babel >=1.3
    - iso8601 >=0.1.9
    - oslo.config <1.10.0,>=1.9.3
    - oslo.i18n <1.6.0,>=1.5.0
    - oslo.utils <1.5.0,>=1.4.0
    - posix_ipc
    - six >=1.9.0
    - "retrying !=1.3.0,>=1.2.3"

test:
  # Python imports
  imports:
    - oslo_concurrency.lockutils
    - oslo_concurrency.processutils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'oslo.concurrency library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
